"""
Claude LLM Explanation and Multi-Turn Analyst Chat Models.
"""

from django.db import models
from apps.alerts.models import Alert


class Explanation(models.Model):
    """
    Evidence-grounded explanation generated by Claude API for a specific Alert.
    """
    alert = models.OneToOneField(Alert, on_delete=models.CASCADE, related_name="explanation")
    evidence_object = models.JSONField(help_text="Structured SHAP, score, and baseline trend evidence")
    explanation_text = models.TextField(help_text="3-5 sentence plain-English explanation")
    faithfulness_score = models.FloatField(default=0.95, help_text="FaithLens faithfulness score (0.0 to 1.0)")
    model_name = models.CharField(max_length=100, default="claude-3-5-sonnet-20241022")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "explanations_explanation"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"Explanation for Alert #{self.alert_id} (Score: {self.faithfulness_score})"


class ChatSession(models.Model):
    """
    Multi-turn conversation session between a security analyst and Claude regarding an alert.
    """
    alert = models.ForeignKey(Alert, on_delete=models.CASCADE, related_name="chat_sessions")
    analyst_name = models.CharField(max_length=150, default="Security Analyst")
    session_token = models.CharField(max_length=100, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "explanations_chatsession"
        ordering = ["-updated_at"]

    def __str__(self) -> str:
        return f"Chat Session: Alert #{self.alert_id} ({self.analyst_name})"


class ChatMessage(models.Model):
    """
    Single message bubble in an analyst-AI conversation.
    """
    ROLE_CHOICES = [
        ("user", "Security Analyst"),
        ("assistant", "Claude AI Assistant"),
        ("system", "System Grounding Prompt"),
    ]

    session = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name="messages")
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    content = models.TextField()
    evidence_grounded = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "explanations_chatmessage"
        ordering = ["created_at"]

    def __str__(self) -> str:
        return f"[{self.role.upper()}] {self.content[:40]}..."
