"""
Claude LLM Explanation and Multi-Turn Analyst Chat Models.
"""

import hashlib
import json
from django.db import models
from apps.alerts.models import Alert


class Explanation(models.Model):
    """
    Evidence-grounded explanation generated by Claude API for a specific Alert.
    Supports asynchronous Celery job tracking with SHA-256 evidence hashing for deduplication.
    """
    STATUS_CHOICES = [
        ("PENDING", "Pending (Queued)"),
        ("PROCESSING", "Processing (In-Flight)"),
        ("COMPLETED", "Completed (Ready)"),
        ("FAILED", "Failed (Error)"),
    ]

    alert = models.ForeignKey(Alert, on_delete=models.CASCADE, related_name="explanations")
    evidence_hash = models.CharField(max_length=64, db_index=True, help_text="SHA-256 of canonical evidence JSON")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="PENDING", db_index=True)
    text = models.TextField(blank=True, default="", help_text="3-5 sentence plain-English explanation")
    error = models.TextField(null=True, blank=True, help_text="Failure reason or exception message")
    attempts = models.SmallIntegerField(default=0, help_text="Number of Celery execution attempts")
    evidence_object = models.JSONField(default=dict, blank=True, help_text="Structured SHAP, score, and baseline trend evidence")
    faithfulness_score = models.FloatField(default=0.95, help_text="FaithLens faithfulness score (0.0 to 1.0)")
    model_name = models.CharField(max_length=100, default="claude-3-5-sonnet-20241022")
    created_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "explanations_explanation"
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(fields=["alert", "evidence_hash"], name="unique_alert_evidence_hash")
        ]

    def __str__(self) -> str:
        return f"Explanation #{self.id} (Alert #{self.alert_id}) [{self.status}]"

    @property
    def explanation_text(self) -> str:
        """Backward compatibility for existing code expecting explanation_text."""
        return self.text

    @explanation_text.setter
    def explanation_text(self, value: str) -> None:
        self.text = value

    @staticmethod
    def compute_evidence_hash(evidence_payload: dict) -> str:
        """
        Compute SHA-256 hash of canonical evidence JSON with sorted keys.
        Guarantees identical payloads produce identical hashes for duplicate protection.
        """
        canonical_bytes = json.dumps(evidence_payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
        return hashlib.sha256(canonical_bytes).hexdigest()


class ChatSession(models.Model):
    """
    Multi-turn conversation session between a security analyst and Claude regarding an alert.
    """
    alert = models.ForeignKey(Alert, on_delete=models.CASCADE, related_name="chat_sessions")
    analyst_name = models.CharField(max_length=150, default="Security Analyst")
    session_token = models.CharField(max_length=100, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "explanations_chatsession"
        ordering = ["-updated_at"]

    def __str__(self) -> str:
        return f"Chat Session: Alert #{self.alert_id} ({self.analyst_name})"


class ChatMessage(models.Model):
    """
    Single message bubble in an analyst-AI conversation.
    """
    ROLE_CHOICES = [
        ("user", "Security Analyst"),
        ("assistant", "Claude AI Assistant"),
        ("system", "System Grounding Prompt"),
    ]

    session = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name="messages")
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    content = models.TextField()
    evidence_grounded = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "explanations_chatmessage"
        ordering = ["created_at"]

    def __str__(self) -> str:
        return f"[{self.role.upper()}] {self.content[:40]}..."
